"""English help for hadith grading terms and book titles, for readers who do not read Arabic.

Grading terms: the English is the English headword in Jamhara, «موسوعة الجمهرة - مفردات المحتوى الإسلامي» (islamic-content.com/dictionary),
the term dictionary named in the challenge's scientific package, copied verbatim with a link to the entry.
Where Jamhara has no English entry for the hadith sense of a term, no English is shown and the link goes to
its Arabic entry. Nothing here is generated by the model, and the scholar's Arabic wording is always shown
verbatim; the English only says what the term means. Each term also has a category (accepted, weak, ...),
the tool's grouping used for colour and for noting that gradings differ; the grouping awaits review by
the team's Sharia specialist.
"""
import re

from .normalize import normalize_ar

JAMHARA = "https://islamic-content.com/dictionary/word/"

# (normalized term, category, Jamhara entry id, Jamhara's English headword or None, transliteration).
# The transliteration only spells the Arabic term in Latin letters (as English-speaking Muslims say it); it adds no meaning.
# Longer terms first so «حسن صحيح» wins over «صحيح». Every id and headword was checked on the live site
# on 2 Oct 2026. Some entries have an English page for another sense of the word (for example 6166 «الصحيح»
# is "The correct view", 10238 «الموضوع» is "Subject matter", 1984 «باطل» is "Invalid", 10109 «المنكر» is
# "Evil, wrong"): for those the English headword is not used and the link goes to the Arabic entry, whose
# definition is the hadith sense.
GRADE_TERMS = [
    ("لا اصل له", "fabricated", 8302, "It has no basis", "la asla lah"),
    ("ليس له اصل", "fabricated", 8568, "Has no origin", "laysa lahu asl"),
    ("موضوع", "fabricated", 10238, None, "mawdu'"),
    ("مكذوب", "fabricated", None, None, "makdhub"),
    ("كذب", "fabricated", 8140, None, "kadhib"),
    ("باطل", "fabricated", 1984, None, "batil"),
    ("ضعيف جدا", "very_weak", 6481, "Very weak", "da'if jiddan"),
    ("منكر", "very_weak", 10109, None, "munkar"),
    ("متروك", "very_weak", 8754, "Discarded", "matruk"),
    ("واه", "very_weak", None, None, "wahin"),
    ("حسن صحيح", "authentic", 4330, "Good, authentic", "hasan sahih"),
    ("صحيح لغيره", "authentic", 6182, "Authentic with others", "sahih li-ghayrihi"),
    ("حسن لغيره", "good", 4335, "Good with others", "hasan li-ghayrihi"),
    ("صحيح", "authentic", 6166, None, "sahih"),
    ("ثابت", "authentic", 3600, "Confirmed", "thabit"),
    ("حسن", "good", 4308, "Good", "hasan"),
    ("جيد", "good", None, None, "jayyid"),
    ("لا باس به", "good", None, None, "la ba'sa bih"),  # Jamhara's 8315 is about a narrator, not a hadith
    ("رجاله ثقات", "narrators", 5154, "Of reliable narrators", "rijaluhu thiqat"),
    ("لا يصح", "weak", 8359, "Unauthentic", "la yasihh"),
    ("لا يثبت", "weak", 8336, "It cannot be confirmed", "la yathbut"),
    ("ضعيف", "weak", 6473, "Weak", "da'if"),
    ("شاذ", "weak", 5849, "Irregular", "shadhdh"),
    ("مرسل", "weak", 9289, "Attributed", "mursal"),
    ("منقطع", "weak", 10103, "Disrupted", "munqati'"),
    ("معلول", "weak", 9761, "Defective", "ma'lul"),  # Jamhara's hadith-sense entry is «المعل»
    ("فيه عله", "weak", 6985, None, "fihi 'illa"),
]
# Chain-only gradings that Jamhara has as entries of their own.
CHAIN_TERMS = {
    "صحيح": (6169, "Authentic chain of transmission"),
    "حسن": (4311, "A good chain"),
    "ضعيف": (6474, "Poor chain of transmission"),
}
_CHAIN = re.compile(r"^(اسناده|سنده|اسناد)\b")


def _entry(entry_id: int | None, en: str | None, tr: str) -> dict:
    url = None
    if entry_id:
        url = f"{JAMHARA}{entry_id}/en" if en else f"{JAMHARA}{entry_id}"
    return {"tr": tr, "en": en, "url": url}


def gloss_grade(grade: str) -> dict:
    """Return {"en", "terms": [{"tr", "en", "url"}], "category", "chain_only", "bracketed"}."""
    raw = grade.strip()
    g = normalize_ar(raw)
    found, taken = [], [False] * len(g)
    for term, cat, entry_id, en, tr in GRADE_TERMS:
        for m in re.finditer(rf"(?<!\S){re.escape(term)}(?!\S)", g):
            if any(taken[m.start():m.end()]):
                continue
            taken[m.start():m.end()] = [True] * (m.end() - m.start())
            found.append((m.start(), term, cat, entry_id, en, tr))
    found.sort()
    cats = {f[2] for f in found}
    chain = bool(_CHAIN.match(g))
    terms = []
    if len(cats) == 1:  # more than one judgment in one sentence: the Arabic wording must be read as a whole
        for _, term, _, entry_id, en, tr in found:
            if chain:
                entry_id, en = CHAIN_TERMS.get(term, (None, None))
                tr = f"isnaduhu {tr}"
            e = _entry(entry_id, en, tr)
            if e not in terms:
                terms.append(e)
    en = "; ".join(t["en"] for t in terms if t["en"]) or None
    return {
        "en": en,
        "terms": terms,
        "category": cats.pop() if len(cats) == 1 else ("mixed" if cats else None),
        "chain_only": chain,
        "bracketed": raw.startswith("[") and raw.endswith("]"),
    }


BOOKS = {
    "صحيح البخاري": "Sahih al-Bukhari",
    "صحيح مسلم": "Sahih Muslim",
    "الموطا": "al-Muwatta'",
    "مسند احمد": "Musnad Ahmad",
    "المسند": "al-Musnad",
    "سنن ابي داود": "Sunan Abi Dawud",
    "سنن الترمذي": "Jami' al-Tirmidhi",
    "جامع الترمذي": "Jami' al-Tirmidhi",
    "سنن النسائي": "Sunan al-Nasa'i",
    "سنن ابن ماجه": "Sunan Ibn Majah",
    "سنن الدارقطني": "Sunan al-Daraqutni",
    "المستدرك": "al-Mustadrak",
    "تلخيص المستدرك": "Talkhis al-Mustadrak",
    "سير اعلام النبلاء": "Siyar A'lam al-Nubala'",
    "ميزان الاعتدال": "Mizan al-I'tidal",
    "فتح الباري": "Fath al-Bari",
    "التلخيص الحبير": "al-Talkhis al-Habir",
    "المنتخب من العلل للخلال": "al-Muntakhab min al-'Ilal (al-Khallal)",
    "السلسله الصحيحه": "al-Silsila al-Sahiha",
    "السلسله الضعيفه": "al-Silsila al-Da'ifa",
    "غايه المرام": "Ghayat al-Maram",
    "ارواء الغليل": "Irwa' al-Ghalil",
    "مشكاه المصابيح": "Mishkat al-Masabih",
    "عمده التفسير": "'Umdat al-Tafsir",
}
_SHORT = {
    "ابي داود": "Abi Dawud", "الترمذي": "al-Tirmidhi", "النسائي": "al-Nasa'i", "ابن ماجه": "Ibn Majah",
    "الجامع": "al-Jami'", "الترغيب": "al-Targhib", "الادب المفرد": "al-Adab al-Mufrad",
    "ابن حبان": "Ibn Hibban", "ابن خزيمه": "Ibn Khuzayma", "موارد الظمان": "Mawarid al-Zam'an",
}


def gloss_book(book: str) -> str | None:
    b = normalize_ar(book)
    if b in BOOKS:
        return BOOKS[b]
    if b.startswith("تخريج "):
        inner = gloss_book(b[len("تخريج "):])
        return f"Takhrij of {inner}" if inner else None
    for prefix, en in (("صحيح ", "Sahih"), ("ضعيف ", "Da'if")):
        if b.startswith(prefix) and b[len(prefix):] in _SHORT:
            return f"{en} {_SHORT[b[len(prefix):]]}"
    return None
