"""English glosses for hadith grading terms and book titles, for readers who do not read Arabic.

A fixed glossary written by the team, never generated by the model. The scholar's Arabic wording
stays the reference and is always shown verbatim; the gloss only explains the standard meaning
of the terms it contains. Unknown terms get no gloss rather than a guess.
"""
import re

from .normalize import normalize_ar

# (normalized term, English gloss, category). Longer terms first so «حسن صحيح» wins over «صحيح».
GRADE_TERMS = [
    ("لا اصل له", "no basis (baseless)", "fabricated"),
    ("ليس له اصل", "no basis (baseless)", "fabricated"),
    ("موضوع", "mawdu' (fabricated)", "fabricated"),
    ("مكذوب", "a fabrication", "fabricated"),
    ("كذب", "a fabrication", "fabricated"),
    ("باطل", "batil (false)", "fabricated"),
    ("ضعيف جدا", "da'if jiddan (very weak)", "very_weak"),
    ("منكر", "munkar (rejected)", "very_weak"),
    ("متروك", "matruk (abandoned)", "very_weak"),
    ("واه", "wahin (very weak)", "very_weak"),
    ("حسن صحيح", "hasan sahih (authentic)", "authentic"),
    ("صحيح لغيره", "sahih li-ghayrihi (authentic through supporting chains)", "authentic"),
    ("حسن لغيره", "hasan li-ghayrihi (good through supporting chains)", "good"),
    ("صحيح", "sahih (authentic)", "authentic"),
    ("ثابت", "thabit (established)", "authentic"),
    ("حسن", "hasan (good)", "good"),
    ("جيد", "jayyid (good)", "good"),
    ("لا باس به", "acceptable", "good"),
    ("رجاله ثقات", "its narrators are trustworthy", "narrators"),
    ("لا يصح", "not authentic", "weak"),
    ("لا يثبت", "not established", "weak"),
    ("ضعيف", "da'if (weak)", "weak"),
    ("شاذ", "shadhdh (anomalous)", "weak"),
    ("مرسل", "mursal (chain lacks the Companion)", "weak"),
    ("منقطع", "munqati' (broken chain)", "weak"),
    ("معلول", "has a hidden defect", "weak"),
    ("فيه عله", "has a hidden defect", "weak"),
]
_CHAIN = re.compile(r"^(اسناده|سنده|اسناد)\b")


def gloss_grade(grade: str) -> dict:
    """Return {"en": str | None, "category": str | None, "chain_only": bool, "bracketed": bool}."""
    raw = grade.strip()
    g = normalize_ar(raw)
    found, taken = [], [False] * len(g)
    for term, en, cat in GRADE_TERMS:
        for m in re.finditer(rf"(?<!\S){re.escape(term)}(?!\S)", g):
            if any(taken[m.start():m.end()]):
                continue
            taken[m.start():m.end()] = [True] * (m.end() - m.start())
            found.append((m.start(), en, cat))
    found.sort()
    cats = {c for _, _, c in found}
    chain = bool(_CHAIN.match(g))
    en = "; ".join(dict.fromkeys(e for _, e, _ in found)) or None
    if len(cats) > 1:
        en = None  # more than one judgment in one sentence: the Arabic wording must be read as a whole
    if en and chain:
        en = f"its chain of narration: {en}"
    return {
        "en": en,
        "category": cats.pop() if len(cats) == 1 else ("mixed" if cats else None),
        "chain_only": chain,
        "bracketed": raw.startswith("[") and raw.endswith("]"),
    }


BOOKS = {
    "صحيح البخاري": "Sahih al-Bukhari",
    "صحيح مسلم": "Sahih Muslim",
    "الموطا": "al-Muwatta'",
    "مسند احمد": "Musnad Ahmad",
    "المسند": "al-Musnad",
    "سنن ابي داود": "Sunan Abi Dawud",
    "سنن الترمذي": "Jami' al-Tirmidhi",
    "جامع الترمذي": "Jami' al-Tirmidhi",
    "سنن النسائي": "Sunan al-Nasa'i",
    "سنن ابن ماجه": "Sunan Ibn Majah",
    "سنن الدارقطني": "Sunan al-Daraqutni",
    "المستدرك": "al-Mustadrak",
    "تلخيص المستدرك": "Talkhis al-Mustadrak",
    "سير اعلام النبلاء": "Siyar A'lam al-Nubala'",
    "ميزان الاعتدال": "Mizan al-I'tidal",
    "فتح الباري": "Fath al-Bari",
    "التلخيص الحبير": "al-Talkhis al-Habir",
    "المنتخب من العلل للخلال": "al-Muntakhab min al-'Ilal (al-Khallal)",
    "السلسله الصحيحه": "al-Silsila al-Sahiha",
    "السلسله الضعيفه": "al-Silsila al-Da'ifa",
    "غايه المرام": "Ghayat al-Maram",
    "ارواء الغليل": "Irwa' al-Ghalil",
    "مشكاه المصابيح": "Mishkat al-Masabih",
    "عمده التفسير": "'Umdat al-Tafsir",
}
_SHORT = {
    "ابي داود": "Abi Dawud", "الترمذي": "al-Tirmidhi", "النسائي": "al-Nasa'i", "ابن ماجه": "Ibn Majah",
    "الجامع": "al-Jami'", "الترغيب": "al-Targhib", "الادب المفرد": "al-Adab al-Mufrad",
    "ابن حبان": "Ibn Hibban", "ابن خزيمه": "Ibn Khuzayma", "موارد الظمان": "Mawarid al-Zam'an",
}


def gloss_book(book: str) -> str | None:
    b = normalize_ar(book)
    if b in BOOKS:
        return BOOKS[b]
    if b.startswith("تخريج "):
        inner = gloss_book(b[len("تخريج "):])
        return f"Takhrij of {inner}" if inner else None
    for prefix, en in (("صحيح ", "Sahih"), ("ضعيف ", "Da'if")):
        if b.startswith(prefix) and b[len(prefix):] in _SHORT:
            return f"{en} {_SHORT[b[len(prefix):]]}"
    return None
