"""The adhkar and du'as on «الأذكار الموثّقة», before verification.

Each hadith item is the dhikr's words as commonly circulated, with the count the narration gives, and the
book it is commonly cited from (`cited`). Nothing here is shown as is: scripts/build_adhkar.py checks every item
with Tathabbut against Dorar, keeps it only if an authentic grading by the approved scholars was found on a
narration containing every word of it, and records that grading verbatim with its link. Quran items are taken
from the Mushaf by reference, never typed.
"""

CATEGORIES = [
    ("morning", "أذكار الصباح", "Morning adhkar"),
    ("evening", "أذكار المساء", "Evening adhkar"),
    ("after_prayer", "أذكار بعد الصلاة", "After the prayer"),
    ("in_prayer", "أذكار الصلاة", "In the prayer"),
    ("waking", "أذكار الاستيقاظ", "On waking"),
    ("sleep", "أذكار النوم", "Before sleep"),
    ("prophet", "من دعاء الرسول ﷺ", "From the Prophet's du'a ﷺ"),
    ("quran_dua", "أدعية من القرآن", "Du'as from the Quran"),
    ("ruqya_quran", "الرقية بالقرآن", "Ruqyah from the Quran"),
    ("ruqya_sunnah", "الرقية بالسنة", "Ruqyah from the Sunnah"),
    ("praise", "الحمد والثناء", "Praise"),
    ("istighfar", "الاستغفار", "Seeking forgiveness"),
    ("comprehensive", "أدعية شاملة", "Comprehensive du'as"),
    ("ease", "أدعية التيسير", "Du'as for ease"),
    ("sick", "أدعية المريض", "For the sick"),
    ("deceased", "أدعية الميت", "For the deceased"),
]

# Hadith items: (id, categories, text, count, cited)
HADITH = [
    ("asbahna", ["morning"], "أصبحنا وأصبح الملك لله والحمد لله لا إله إلا الله وحده لا شريك له", 1, "مسلم"),
    ("amsayna", ["evening"], "أمسينا وأمسى الملك لله والحمد لله لا إله إلا الله وحده لا شريك له", 1, "مسلم"),
    ("bika_asbahna", ["morning"], "اللهم بك أصبحنا وبك أمسينا وبك نحيا وبك نموت وإليك النشور", 1, "الترمذي وأبو داود"),
    ("bika_amsayna", ["evening"], "اللهم بك أمسينا وبك أصبحنا وبك نحيا وبك نموت وإليك المصير", 1, "الترمذي وأبو داود"),
    ("sayyid_istighfar", ["morning", "evening", "istighfar"],
     "اللهم أنت ربي لا إله إلا أنت خلقتني وأنا عبدك وأنا على عهدك ووعدك ما استطعت أعوذ بك من شر ما صنعت أبوء لك بنعمتك علي وأبوء بذنبي فاغفر لي فإنه لا يغفر الذنوب إلا أنت", 1, "البخاري"),
    ("afini", ["morning", "evening"], "اللهم عافني في بدني اللهم عافني في سمعي اللهم عافني في بصري لا إله إلا أنت", 3, "أبو داود"),
    ("afw_afiya", ["morning", "evening", "comprehensive"],
     "اللهم إني أسألك العفو والعافية في الدنيا والآخرة اللهم إني أسألك العفو والعافية في ديني ودنياي وأهلي ومالي", 1, "أبو داود وابن ماجه"),
    ("bismillah_layadur", ["morning", "evening"],
     "بسم الله الذي لا يضر مع اسمه شيء في الأرض ولا في السماء وهو السميع العليم", 3, "أبو داود والترمذي"),
    ("raditu", ["morning", "evening"], "رضيت بالله ربا وبالإسلام دينا وبمحمد نبيا", 3, "أبو داود والترمذي"),
    ("ya_hayy", ["morning", "evening", "ease"], "يا حي يا قيوم برحمتك أستغيث أصلح لي شأني كله ولا تكلني إلى نفسي طرفة عين", 1, "النسائي في عمل اليوم والليلة"),
    ("subhan_bihamdihi_100", ["morning", "evening", "praise"], "سبحان الله وبحمده", 100, "مسلم"),
    ("tahlil_100", ["morning", "praise"], "لا إله إلا الله وحده لا شريك له له الملك وله الحمد وهو على كل شيء قدير", 100, "البخاري ومسلم"),
    ("kalimat_tammat", ["evening", "ruqya_sunnah"], "أعوذ بكلمات الله التامات من شر ما خلق", 3, "مسلم"),
    ("alim_ghayb", ["morning", "evening"],
     "اللهم عالم الغيب والشهادة فاطر السماوات والأرض رب كل شيء ومليكه أشهد أن لا إله إلا أنت أعوذ بك من شر نفسي ومن شر الشيطان وشركه", 1, "أبو داود والترمذي"),
    ("istighfar_3", ["after_prayer"], "أستغفر الله", 3, "مسلم"),
    ("anta_salam", ["after_prayer"], "اللهم أنت السلام ومنك السلام تباركت يا ذا الجلال والإكرام", 1, "مسلم"),
    ("la_mani", ["after_prayer"],
     "لا إله إلا الله وحده لا شريك له له الملك وله الحمد وهو على كل شيء قدير اللهم لا مانع لما أعطيت ولا معطي لما منعت ولا ينفع ذا الجد منك الجد", 1, "البخاري ومسلم"),
    ("tasbih_33", ["after_prayer", "praise"], "سبحان الله والحمد لله والله أكبر", 33, "مسلم"),
    ("aini_dhikrik", ["after_prayer", "comprehensive"], "اللهم أعني على ذكرك وشكرك وحسن عبادتك", 1, "أبو داود والنسائي"),
    ("istiftah", ["in_prayer"], "سبحانك اللهم وبحمدك وتبارك اسمك وتعالى جدك ولا إله غيرك", 1, "أبو داود والترمذي"),
    ("baid", ["in_prayer"], "اللهم باعد بيني وبين خطاياي كما باعدت بين المشرق والمغرب", 1, "البخاري ومسلم"),
    ("ruku", ["in_prayer"], "سبحان ربي العظيم", 3, "مسلم"),
    ("sujud", ["in_prayer"], "سبحان ربي الأعلى", 3, "مسلم"),
    ("subhanaka_ruku", ["in_prayer"], "سبحانك اللهم ربنا وبحمدك اللهم اغفر لي", 1, "البخاري ومسلم"),
    ("ahyana", ["waking"], "الحمد لله الذي أحيانا بعد ما أماتنا وإليه النشور", 1, "البخاري"),
    ("bismika_amut", ["sleep"], "باسمك اللهم أموت وأحيا", 1, "البخاري"),
    ("qini_adhabak", ["sleep"], "اللهم قني عذابك يوم تبعث عبادك", 3, "أبو داود والترمذي"),
    ("bismika_rabbi", ["sleep"], "باسمك رب وضعت جنبي وبك أرفعه إن أمسكت نفسي فارحمها وإن أرسلتها فاحفظها بما تحفظ به عبادك الصالحين", 1, "البخاري ومسلم"),
    ("sleep_tasbih", ["sleep"], "تسبحين ثلاثا وثلاثين وتحمدين ثلاثا وثلاثين وتكبرين أربعا وثلاثين", 1, "البخاري ومسلم"),
    ("huda_tuqa", ["prophet", "comprehensive"], "اللهم إني أسألك الهدى والتقى والعفاف والغنى", 1, "مسلم"),
    ("dunya_hasana", ["prophet", "comprehensive"], "اللهم ربنا آتنا في الدنيا حسنة وفي الآخرة حسنة وقنا عذاب النار", 1, "البخاري ومسلم"),
    ("muqallib", ["prophet", "comprehensive"], "يا مقلب القلوب ثبت قلبي على دينك", 1, "الترمذي"),
    ("zawal_nimatik", ["prophet", "comprehensive"],
     "اللهم إني أعوذ بك من زوال نعمتك وتحول عافيتك وفجاءة نقمتك وجميع سخطك", 1, "مسلم"),
    ("aslih_dini", ["prophet", "comprehensive"],
     "اللهم أصلح لي ديني الذي هو عصمة أمري وأصلح لي دنياي التي فيها معاشي وأصلح لي آخرتي التي فيها معادي", 1, "مسلم"),
    ("hamm_hazan", ["prophet", "ease"],
     "اللهم إني أعوذ بك من الهم والحزن والعجز والكسل والبخل والجبن وضلع الدين وغلبة الرجال", 1, "البخاري"),
    ("ilm_nafi", ["prophet", "comprehensive"], "اللهم إني أسألك علما نافعا ورزقا طيبا وعملا متقبلا", 1, "ابن ماجه"),
    ("la_sahl", ["ease"], "اللهم لا سهل إلا ما جعلته سهلا وأنت تجعل الحزن إذا شئت سهلا", 1, "ابن حبان"),
    ("karb", ["ease"], "لا إله إلا الله العظيم الحليم لا إله إلا الله رب العرش العظيم لا إله إلا الله رب السموات ورب الأرض ورب العرش الكريم", 1, "البخاري ومسلم"),
    ("hasbuna", ["ease"], "حسبنا الله ونعم الوكيل", 1, "البخاري"),
    ("arqika", ["ruqya_sunnah"], "بسم الله أرقيك من كل شيء يؤذيك من شر كل نفس أو عين حاسد الله يشفيك بسم الله أرقيك", 1, "مسلم"),
    ("adhhib_bas", ["ruqya_sunnah", "sick"],
     "اللهم رب الناس أذهب البأس اشفه وأنت الشافي لا شفاء إلا شفاؤك شفاء لا يغادر سقما", 1, "البخاري ومسلم"),
    ("izzat_allah", ["ruqya_sunnah", "sick"], "أعوذ بالله وقدرته من شر ما أجد وأحاذر", 7, "مسلم"),
    ("kalimat_hamma", ["ruqya_sunnah"], "أعيذكما بكلمات الله التامة من كل شيطان وهامة ومن كل عين لامة", 1, "البخاري"),
    ("la_bas_tahur", ["sick"], "لا بأس طهور إن شاء الله", 1, "البخاري"),
    ("asal_allah_yashfik", ["sick"], "أسأل الله العظيم رب العرش العظيم أن يشفيك", 7, "أبو داود والترمذي"),
    ("bismillah_3_pain", ["sick"], "ضع يدك على الذي تألم من جسدك وقل بسم الله ثلاثا", 1, "مسلم"),
    ("hamd_kathir", ["praise"], "الحمد لله حمدا كثيرا طيبا مباركا فيه", 1, "البخاري"),
    ("adad_khalqih", ["praise"], "سبحان الله وبحمده عدد خلقه ورضا نفسه وزنة عرشه ومداد كلماته", 3, "مسلم"),
    ("baqiyat", ["praise"], "سبحان الله والحمد لله ولا إله إلا الله والله أكبر", 1, "مسلم"),
    ("hawqala", ["praise"], "لا حول ولا قوة إلا بالله", 1, "البخاري ومسلم"),
    ("kalimatan", ["praise"], "سبحان الله وبحمده سبحان الله العظيم", 1, "البخاري ومسلم"),
    ("astaghfiru_atub", ["istighfar"], "أستغفر الله وأتوب إليه", 1, "البخاري"),
    ("rabbi_ghfir_tub", ["istighfar"], "رب اغفر لي وتب علي إنك أنت التواب الرحيم", 100, "أبو داود والترمذي"),
    ("hayy_qayyum_istighfar", ["istighfar"], "أستغفر الله الذي لا إله إلا هو الحي القيوم وأتوب إليه", 1, "أبو داود والترمذي"),
    ("zalamtu", ["istighfar", "prophet"],
     "اللهم إني ظلمت نفسي ظلما كثيرا ولا يغفر الذنوب إلا أنت فاغفر لي مغفرة من عندك وارحمني إنك أنت الغفور الرحيم", 1, "البخاري ومسلم"),
    ("janaza", ["deceased"],
     "اللهم اغفر له وارحمه وعافه واعف عنه وأكرم نزله ووسع مدخله واغسله بالماء والثلج والبرد ونقه من الخطايا كما نقيت الثوب الأبيض من الدنس", 1, "مسلم"),
    ("janaza_hayyina", ["deceased"],
     "اللهم اغفر لحينا وميتنا وشاهدنا وغائبنا وصغيرنا وكبيرنا وذكرنا وأنثانا", 1, "أبو داود والترمذي"),
    ("ummu_salama", ["deceased"], "اللهم اغفر لأبي سلمة وارفع درجته في المهديين", 1, "مسلم"),
    ("tathbit_dafn", ["deceased"], "استغفروا لأخيكم وسلوا له بالتثبيت فإنه الآن يسأل", 1, "أبو داود"),
    ("musiba", ["deceased"], "إنا لله وإنا إليه راجعون اللهم أجرني في مصيبتي وأخلف لي خيرا منها", 1, "مسلم"),
    ("asma_99", ["names"], "إن لله تسعة وتسعين اسما مائة إلا واحدا من أحصاها دخل الجنة", 1, "البخاري ومسلم"),
]

# Evidence for placing a Quran item under an occasion: a hadith, verified like the adhkar (its own words, an
# authentic grading, the occasion named in the narration). Not shown as a dhikr; shown as the verse's evidence.
HADITH += [
    ("ev_kursi_sleep", ["sleep"], "إذا أويت إلى فراشك فاقرأ آية الكرسي", 1, "البخاري"),
    ("ev_kursi_prayer", ["after_prayer"], "من قرأ آية الكرسي في دبر كل صلاة مكتوبة لم يمنعه من دخول الجنة إلا أن يموت", 1, "النسائي في الكبرى"),
    ("ev_muawwidhat_day", ["morning", "evening"], "قل هو الله أحد والمعوذتين حين تمسي وحين تصبح ثلاث مرات تكفيك من كل شيء", 3, "أبو داود والترمذي"),
    ("ev_muawwidhat_sleep", ["sleep"], "كان إذا أوى إلى فراشه كل ليلة جمع كفيه ثم نفث فيهما", 1, "البخاري"),
    ("ev_muawwidhat_ruqya", ["ruqya_quran"], "كان إذا اشتكى يقرأ على نفسه بالمعوذات وينفث", 1, "البخاري"),
    ("ev_fatiha_ruqya", ["ruqya_quran"], "وما يدريك أنها رقية", 1, "البخاري"),
]

# Quran items: (id, {category: evidence hadith id, or None when the verse is itself the du'a}, surah, from, to)
QURAN = [
    ("ayat_kursi", {"after_prayer": "ev_kursi_prayer", "sleep": "ev_kursi_sleep"}, 2, 255, 255),
    ("ikhlas", {"morning": "ev_muawwidhat_day", "evening": "ev_muawwidhat_day", "sleep": "ev_muawwidhat_sleep", "ruqya_quran": "ev_muawwidhat_ruqya"}, 112, 1, 4),
    ("falaq", {"morning": "ev_muawwidhat_day", "evening": "ev_muawwidhat_day", "sleep": "ev_muawwidhat_sleep", "ruqya_quran": "ev_muawwidhat_ruqya"}, 113, 1, 5),
    ("nas", {"morning": "ev_muawwidhat_day", "evening": "ev_muawwidhat_day", "sleep": "ev_muawwidhat_sleep", "ruqya_quran": "ev_muawwidhat_ruqya"}, 114, 1, 6),
    ("fatiha", {"ruqya_quran": "ev_fatiha_ruqya"}, 1, 1, 7),
    ("q_dunya_hasana", {"quran_dua": None}, 2, 201, 201),
    ("q_baqara_end", {"quran_dua": None}, 2, 285, 286),
    ("q_la_tuzigh", {"quran_dua": None}, 3, 8, 8),
    ("q_israfana", {"quran_dua": None}, 3, 147, 147),
    ("q_zalamna", {"quran_dua": None, "istighfar": None}, 7, 23, 23),
    ("q_hasbiya", {"ease": None}, 9, 129, 129),
    ("q_muqim_salat", {"quran_dua": None}, 14, 40, 41),
    ("q_ishrah", {"quran_dua": None, "ease": None}, 20, 25, 28),
    ("q_zidni", {"quran_dua": None}, 20, 114, 114),
    ("q_ayyub", {"quran_dua": None, "sick": None}, 21, 83, 83),
    ("q_yunus", {"quran_dua": None, "ease": None, "istighfar": None}, 21, 87, 87),
    ("q_khayr_rahimin", {"quran_dua": None, "istighfar": None}, 23, 118, 118),
    ("q_qurrat_ayun", {"quran_dua": None}, 25, 74, 74),
    ("q_yashfin", {"sick": None}, 26, 80, 80),
    ("q_ikhwanina", {"quran_dua": None, "deceased": None}, 59, 10, 10),
]
